### PR TITLE
Add npm prepare script to forward to nps build

### PR DESCRIPTION
**Pull request by jondkinney**
npm has the ability to install packages from github, but without a prepare script to run the build process, those packages won't work properly when installed in a project. See here for more details: https://blog.jim-nielsen.com/2018/installing-and-building-an-npm-package-from-github/#installing-and-building-packages-with-npm-from-github

I needed to add this in my fork to get around this issue: https://github.com/prettier/prettier-eslint/pull/194 

Without the fix provided in that issue, I get the following warning: `Warning: React version not specified in eslint-plugin-react settings` and I'm trying to use https://github.com/prettier/prettier-eslint-cli with Vim to auto-format my code. When shelling out and using the CLI, that warning is thrown and added at the top of the Vim buffer on each save.

I also have another PR for https://github.com/prettier/prettier-eslint-cli that allows for having that project reference this project as a peerDependency so that we can actually pull this fix into that other project. See here: https://github.com/prettier/prettier-eslint-cli/pull/144

Without specifying `prettier-eslint` as a peerDependency of `prettier-eslint-cli` the problem is that `prettier-eslint-cli` will install its own version of `prettier-eslint` and that old version doesn't have the fix specified in https://github.com/prettier/prettier-eslint/pull/194

If I'm making this way harder than it needs to be please let me know. But this all seems to work. I only have one version of `prettier-eslint` installed in my node_modules folder. `prettier-eslint-cli`'s node_modules folder does _not_ have its own `prettier-eslint`, and the error is gone!

### CODE REVIEW

**Comment by jondkinney** [comment]
Hi @azz, thanks for the response! That's true, but right now this doesn't run build scripts for either package manager, so my thought was if you need that functionality, install this with npm for the time being. Unless you're suggesting to be consistent we shouldn't do it for either? It looks like yarn is working on fixing things as well: https://github.com/yarnpkg/yarn/issues/5235.

**Comment by chinesedfan** [comment]
@jondkinney If using yarn, [resolutions](https://yarnpkg.com/en/docs/selective-version-resolutions) can help specify a certain version(includes installing from Github) of `prettier-eslint`. And you can build files first in your fork.

What's more, #211 has fixed the CI and a new release should be not far away.

**Comment by jondkinney** [comment]
Looks like these commits somehow got pulled into master but then reverted without actually merging this PR? Perhaps things were fixed upstream making this no longer necessary, but curious about some feedback on this PR so we can close it if that's all that's left to do. Thanks!

**Comment by zimme** [comment]
I added these changes but something went wrong so I reverted the changes and kept this PR open.

**Pull request closed without merging**
