### PR TITLE
Upgrade ESLint to 6

### LINKED ISSUE #222: Not working properly width eslint 6
**Versions**:

- `prettier-eslint` 9.0.0:
- `node` 10.15.3:
- `npm` (or `yarn`) version: 6.10.0

**Have you followed [the debugging tips](https://github.com/prettier/prettier-eslint/blob/master/README.md#debugging-issues)?**

Yes

**Relevant code or config**
https://github.com/prettier/prettier-eslint/blob/c87b69b769c59bcea0d96c87dddb6a4925085d8a/src/index.js#L225-L243
```diff
  const eslintOptions = {};
  if (filePath) {
    eslintOptions.cwd = path.dirname(filePath);
  }
  logger.trace(
    oneLine`
      creating ESLint CLI Engine to get the config for
      "${filePath || process.cwd()}"
    `
  );
  const cliEngine = getESLintCLIEngine(eslintPath, eslintOptions);
  try {
    logger.debug(`getting eslint config for file at "${filePath}"`);
    const config = cliEngine.getConfigForFile(filePath);
+   config.cwd = eslintOptions.cwd
    logger.trace(
      `eslint config for "${filePath}" received`,
      prettyFormat(config)
    );
    return config;
```

**What I did:**

Support eslint 6

**What happened:**
when I set "prettier.eslintIntegration": true
then the error happend in VSCode
```
Failed to load plugin 'standard' declared in 'CLIOptions'/Users/nashaofu/edc/web/src/c.js:: Cannot find module 'eslint-plugin-standard'
Require stack:
- __placeholder__.js
```
My eslint configuration is as follows:
```js
module.exports = {
  root: true,
  parser: 'babel-eslint',
  env: {
    es6: true,
    node: true,
    commonjs: true
  },
  extends: ['standard']
}
```
**Problem description:**

The CWD of the process pointed incorrectly

**Suggested solution:**
details https://github.com/prettier/prettier-vscode/issues/869

### PR DESCRIPTION
**Pull request by kylemh**
Resolves #222 

# Summary
For those uninterested in seeing the conversation below, we simply upgraded the dependency and removed an assertion regarding the number of times `fs.readFileSync` is called, as it is an integration detail that ESLint controls - not this library.

# Original Post
So... logging the calls of `fsMock.readFileSync` yields:

an array of 5 calls, 4 of which relate to .eslintignore

The following test `logs error if it cannot read the file...` sets and resets the mock at the test-level, instead of the test lifecycle; however, when I attempt this workaround...

```javascript
test('reads text from fs if filePath is provided but not text', () => {
  const originalMock = fsMock.readFileSync;
  fsMock.readFileSync = jest.fn();

  const filePath = '/blah-blah/some-file.js';
  format({ filePath });

  expect(fsMock.readFileSync).toHaveBeenCalledWith(filePath, 'utf8');

  // one hit to get the file and one for the eslintignore
  expect(fsMock.readFileSync).toHaveBeenCalledTimes(2);

  fsMock.readFileSync = originalMock;
});
```

I'm met with many other broken tests:

Screen Shot 2019-08-19 at 3 10 05 PM
Screen Shot 2019-08-19 at 3 09 55 PM
Screen Shot 2019-08-19 at 3 09 33 PM

I skimmed the changelog for ESLint since v5, but couldn't find a reasoning for the increased calls; so I'm left to imagine that

a) It is invalid and the way the tests are written currently need a massive overhaul to avoid leaking into other . tests.

**OR**

b) It is valid, but I'm unsure how to document the extra calls.

### CODE REVIEW

**Comment by RobertPaul01** [comment]
Can this be merged?

**Comment by kylemh** [comment]
@RobertPaul01 I feel like you didn’t read anything.

No it can’t be merged.

**Comment by jakeleventhal** [comment]
@kylemh lmfao

**Comment by RobertPaul01** [comment]
The library seems to work fine with the updated dependency. The janky tests should be turned off.

**Comment by RobertPaul01** [comment]
The library seems to work fine with the updated dependency. The janky tests should be turned off or updated.

This is the commit that introduces the additional ignore file reads. https://github.com/eslint/eslint/commit/6ae21a4bfe5a1566f787fbad798182a524b96d28

Specifically, a new IgnoredPaths is created in the construtor of the CLIEngine now and not just in the executeOnText and `getESLintCLIEngine` creates a new CLIEngine object every call.

Also, the FileEnumerator will create a new IgnoredPath object.

During that test, 3 `new CLIEngine` are made, one in `/blah-blah/` which has no .eslintignore. 2 are made in the ~/ directory which leads to the eslintIgnore being read a total of 4 times.

Also, you debugged the test incorrectly. You need to do this to not crash all the test like you did because you stubbed the readFileSync to an empty function.
```
test('reads text from fs if filePath is provided but not text', () => {
  const originalMock = fsMock.readFileSync;
  fsMock.readFileSync = jest.fn((...args) => originalMock(...args));

  const filePath = '/blah-blah/some-file.js';
  format({ filePath });

  expect(fsMock.readFileSync).toHaveBeenCalledWith(filePath, 'utf8');

  // one hit to get the file and one for the eslintignore
  expect(fsMock.readFileSync).toHaveBeenCalledTimes(2);

  fsMock.readFileSync = originalMock;
});
```

**Comment by kylemh** [comment]
Hell yeah, well why didn't you say so!?

>Also, you debugged the test incorrectly. You need to do this to not crash all the test like you did because you stubbed the readFileSync to an empty function.

This is totally correct - didn't realize fs was mocked separately as part of the Jest setup, so I needed to pass it the mock implementation, or - better yet - I'll just spy on the original mock fn implementation.

Let's merge this @zimme  💃

**Comment by kylemh** [comment]
Hell yeah, well why didn't you say so!?

>Also, you debugged the test incorrectly. You need to do this to not crash all the test like you did because you stubbed the readFileSync to an empty function.

This is totally correct - didn't realize fs was mocked separately as part of the Jest setup, so I needed to pass it the mock implementation, or - better yet - I'll just spy on the original mock fn implementation.

Unfortunately, even with the corrections (tried both the `done fn` implementation you showed and the spy method I tried), but am still seeing 5 function calls versus 2.

> The janky tests should be turned off or updated.

Doesn't seem like the safest strategy, which is why I tried opening up this issue for discussion. I agree with you and think these tests are "janky", but the library main contributors should be the one to see in finality.

**Comment by numso** [comment]
@kylemh: Based on what @RobertPaul01 wrote, the way prettier-eslint interacts with eslint@6 causes .eslintignore to be read multiple times during the test. That test should now assert that `readFileSync` was called 5 times.

IMHO The test in question is testing more of the internal details of eslint than it should. That test is just trying to ensure that `format`, given a filePath, reads and uses the file at that filePath. That being the case, I believe the call count assertion (`expect(readFileSyncMockSpy).toHaveBeenCalledTimes(5);`) is unneeded and should be removed.

**Comment by kylemh** [comment]
Thank you all for making it a discussion y'all ❤️
I agree that the **most important** assertion is that `readFileSync` is called and with the right parameters, but not necessarily the number of calls.

@zimme if you feel asserting the number of calls is necessary let me know, and I'll add a comment to this pull request as contextual information. Otherwise, this PR should be ready.

**Comment by zimme** [comment]
I'll make sure to carve out some time this week for this so we can get a new major version out with support for eslint 6

**Comment by JSanchezIO** [comment]
Has any progress been made on this?

**Comment by zimme** [comment]
I started to look at this today, however family life intervened and here we are me hoping to get a few hours available this week to look at this and hopefully merge

**Comment by kylemh** [comment]
Clearly zimme will get to it when he can. No need to request for more updates.

**Comment by tweet** [comment]
@zimme Any update for this PR?

**Comment by zimme** [comment]
I will try my best to test and merge this within a week.

**Comment by dimitropoulos** [comment]
@zimme is there any way I can help?

**Comment by blueandhack** [comment]
> I will try my best to test and merge this within a week.

Hi Simon, first I want to say, thank you! we are still waiting for you. I know this is hard that maintainers to maintain a popular public repository, but you know, a lot of people and repository waiting for this merge. Thank you again!

**Comment by tomkel** [comment]
Feel free to put up a donation link so everyone who wants in can chip in to get it done

**Comment by kylemh** [comment]
Just because it's ready to be merged doesn't mean it's ready to be used in everybody's application. 

We had a discussion at the top of the PR on a point that we _think_ we have a good understanding of now, but - as an author of a popular open source library - the hesitation becomes around not wanting to bump versions before they're as certain as possible. 

If this ships and actually leads to bugs, now the author has created their own stress to correct everything ASAP. If they don't, issues increase and notifications blow up increasing more stress.


Please stop bumping this thread. They'll release it when they release it.

**Comment by pelotom** [comment]
Why not just release under a beta tag and let early adopters find the bugs for you? Seems like everyone's happy then...

**Comment by vykjn** [comment]
Apparently, if changing below in `eslint-plugin-prettier/eslint-plugin-prettier.js` seems to pass on the formatted code for further linting/manipulation:
```diff
let prettierSource;
    try {
--        prettierSource = prettier.format(source, prettierOptions);
++      return prettierSource
```

Haven't done much testing, but the advantages are obvious if it can be as easy as changing a few lines of code in that file... Or am I being naive?

**Comment by kylemh** [comment]
@zimme care to release a beta tag with this merged? I can subscribe to the repo and pay attention to issues. If we get any from the beta, I can make the reversion PR and ping you.

**Comment by jamesblack** [comment]
> Clearly zimme will get to it when he can. No need to request for more updates.

**Comment by DarkMikey** [comment]
Sorry to ask, but what is the workaround to get prettier to work with eslint 6?

**Comment by kylemh** [comment]
Assuming you install the relevant dependencies, you’ll want a lint config like this:

```js

module.exports = {
  env: {
    browser: true,
    commonjs: true,
    es6: true,
    jest: true,
    node: true,
  },

  extends: [
    'prettier',
    'prettier/react',
  ],

  parserOptions: {
    ecmaFeatures: {
      jsx: true,
    },
    ecmaVersion: 2018,
    sourceType: 'module',
  },

  plugins: [
    'prettier',
  ],

  rules: {
    // Prettier Plugin Rules
    'prettier/prettier': 'error',
  },
};
```

**Comment by kylemh** [comment]
Ready to merge and tag at your discretion @hamzahamidi

**Comment by hamzahamidi** [comment]
@kylemh it appears the pr no longer passes. I'll take a look

**Comment by hamzahamidi** [comment]
@kylemh The checks pass now

**Comment by hamzahamidi** [comment]
I'll merge this branch

**Comment by numso** [comment]
@hamzahamidi FYI looks like things may have gotten lost in between PRs getting merged and reverted. It looks like master is still pointing to eslint@5

https://github.com/prettier/prettier-eslint/blob/b2ae0878520dbaf93fc7c4faffd120928088c8d6/package.json#L25

**Comment by kylemh** [comment]
Strange. It was here: https://github.com/prettier/prettier-eslint/pull/236/commits/95169c5733c2c36ddd99d896913afc1427fa01de

**Comment by hamzahamidi** [comment]
Ok I'll ready another pr.

**Comment by hamzahamidi** [comment]
https://github.com/prettier/prettier-eslint/pull/337

**Pull request merged**
