### PR TITLE
Use fallbacks for disabled ESLint rules

### PR DESCRIPTION
**Pull request by OliverJAsh**
Fixes https://github.com/prettier/prettier-eslint/issues/97

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks for this! Could you add some tests for your changes?

**Comment by OliverJAsh** [comment]
Sure, I thought I couldn't see any tests, just a folder with mocks... I'll look again!

**Comment by kentcdodds** [comment]
Tests are co-located in this project. See [here](https://github.com/OliverJAsh/prettier-eslint/blob/63ccb2ba606c1c58e74e310c6a2f8799f36bde69/src/utils.test.js)

**Comment by OliverJAsh** [comment]
@kentcdodds Done, see https://github.com/prettier/prettier-eslint/pull/98/commits/2584a75439a5a8df62d8db49f0c92343b4f61463.

**Comment by kentcdodds** [comment]
Ah, it looks like we're still missing some coverage. I like to maintain 100% code coverage on my libraries/tools because it's relatively simple to do. If you're not familiar with code coverage, you can open the report in your browser: `coverage/lcov-report/index.html` that should show you the areas of the code that aren't quite covered yet. Could you add another test to cover what's missing?

**Comment by OliverJAsh** [comment]
@kentcdodds The coverage tool was reporting `else branch not taken`:

image

Upon investigation, I don't think we ever get a `RULE_DISABLED` value at this point. Removing the if statement seems to work, and coverage is back to 100%.

**Comment by kentcdodds** [comment]
Thanks a bunch!

**Comment by kentcdodds** [comment]
Oh, by the way, would you like to [add yourself](../blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) to the [contributors table](../#contributors)? Feel free to open another PR for it :)

**Pull request merged**
