### PR TITLE
[WIP] Let prettier handle json files

### PR DESCRIPTION
**Pull request by zimme**
This will pass through json files to prettier so it can do its thing on them.

### CODE REVIEW

**Comment by zimme** [comment]
My bad, missed running the linter. I'll have a look at the complexity and see what I can do about that.

**Comment by zimme** [comment]
I can't thing of a good way to lower the complexity of this function without making the code less readable. I'll just make the limit higher for this function instead.

Feel free to skip that commit if you see a better way.

**Comment by zimme** [comment]
I'm working on a test case for this and also we need to wait for the next version of prettier before merging this as JSON support isn't in yet.

**Comment by kentcdodds** [comment]
Yeah, that complexity rule is annoying.

**Comment by zimme** [comment]
There I've added a basic test for json, like really basic.

But when running locally with a git checkout of prettier linked I got error about prettier not throwing, but I'm guessing that jests mock setup for `prettier` when using a locally linked package might not work as expected or something.

**Comment by zimme** [comment]
Also, we can't merge this until `prettier´ releases a new version with the added json support.

**Comment by zimme** [comment]
Currently the test is failing because we're not using the latest prettier with json support.

**Comment by kentcdodds** [comment]
Looks like the test is failing. Perhaps you need to use `yarn` to update prettier?

**Comment by kentcdodds** [comment]
screenshot_20170622-140349

**Comment by zimme** [comment]
I know, because there isn't a released version of prettier yet. With the new json support. 😜

**Comment by kentcdodds** [comment]
Oh! Lol! I hadn't seen that had been released yet so I was surprised. Sounds good. We'll wait to merge this until prettier is released.

**Comment by kentcdodds** [comment]
v1.5.0 of prettier was released with json support. Could you run `yarn upgrade prettier` and push the changes to `yarn.lock` and `package.json`? Thanks!

**Comment by zimme** [comment]
Done. We do have some failing tests though, I'm not sure if they're related to my changes or something else that might have changed with prettier?

**Comment by zimme** [comment]
Aah, I guess the tests were failing locally because I had a locally linked package of prettier instead.

**Pull request merged**
