### PR TITLE
Use cwd for create eslint fix

### PR DESCRIPTION
**Pull request by lewisl9029**
This seems to fix https://github.com/prettier/prettier-atom/issues/505

Previously we weren't specifying a `cwd` option for eslint in `createEslintFix`, so the working directory defaulted to where prettier-atom invoked the function, i.e. somewhere in the atom config directory. This ensures we infer the `cwd` from the `filePath` as we do in `getESLintConfig` here: https://github.com/prettier/prettier-eslint/blob/master/src/index.js#L227

The change seems to have broken this test assertion expecting 2 calls to `readFileSync`: https://github.com/prettier/prettier-eslint/commit/d9d190e30b102024950b539052523d5a19285f52#diff-8a18675f0cf6827722b5896d753397b9L356

I updated the test here but wasn't fully sure of the implications. Let me know if this is problematic. Would love to hear other suggestions on how to move forward with this bugfix.

### CODE REVIEW

**Comment by lewisl9029** [comment]
@zimme mind taking a look at this one?

It's meant to fix the most popular issue on prettier-atom with 33 👍 s and 39 comments, affecting a lot of people: https://github.com/prettier/prettier-atom/issues/505

And the fix itself is fairly small: https://github.com/prettier/prettier-eslint/pull/242/files#diff-1fdf421c05c1140f6d71444ea2b27638R173

Thanks!

**Comment by jjosef** [comment]
Is anyone maintaining this project? This is a serious issue.

**Comment by SebiTimeWaster** [comment]
is there maybe a usable fork of this project that has this fix?

**Comment by SebiTimeWaster** [comment]
image

there was no activity in 1 month on this project, i think it is dead.

**Comment by jjosef** [comment]
Probably a good idea. I am unable to at the moment but would be nice to see this happen

**Comment by zimme** [comment]
Will look into this later this week when I'll look into the eslint 6 stuff, if my family life permits me some spare time

**Comment by louisscruz** [comment]
Any update on this? I've just verified that this does in fact solve prettier/prettier-atom#505.

**Comment by digitalmaster** [comment]
Should we fork this plugin?

**Comment by j-f1** [comment]
cc @prettier/eslint

**Comment by zimme** [comment]
Merged in https://github.com/prettier/prettier-eslint/commit/6d4fb2275fa6c3935094e4c127db225537b877a6 with some changes.

Please test `9.0.1` and see if this is solved.

**Pull request closed without merging**
