### PR TITLE
Add test for #138

### PR DESCRIPTION
**Pull request by Robert-Frampton**

### CODE REVIEW

**Comment by zimme** [comment]
What's the difference between this solution and the previous one you closed?

**Comment by Robert-Frampton** [comment]
@zimme the previous solution didn't actually resolve the issue. It wasn't taking eslint's `max-len.tabWidth` into account.

**Comment by Robert-Frampton** [comment]
Also, I'll add another test to address the drop in code coverage.

**Comment by Robert-Frampton** [comment]
Hey @zimme 

Any chance you can merge this? It's a blocker for my team. 

I know that few people are maintaining this package at the moment, I'm open to lending a hand if you're open.

**Comment by zimme** [comment]
There, it should be out now. I got auto release to work. I'm sorry for losing you as an author in the commit. However you're still in the commit history. I'm looking into how to merge the same way Kent was so that I can keep the author on the commits.

**Comment by Robert-Frampton** [comment]
No problem, just glad it's published now.

**Pull request merged**
