### PR TITLE
chore(prettier): update prettier to latest version (0.22.0)

### PR DESCRIPTION
**Pull request by mgmcdermott**
Updated by running `yarn upgrade prettier`

### CODE REVIEW

**Comment by mgmcdermott** [comment]
Build failed due to eslint@^3.17.0 not being installed as a peer dependency.

**Comment by kentcdodds** [comment]
Mind fixing that too? 😄

**Comment by mgmcdermott** [comment]
Yea, no problem. Also going to replace the now deprecated `babel-preset-latest` with `babel-preset-env`

**Comment by mgmcdermott** [comment]
For the build, we can either have travis install eslint separately or add a hard dependency on eslint@^3.17.0. What do you think? Considering the package is named **prettier-eslint** I think it's ok to have a hard dependency on eslint 😄

**Comment by mgmcdermott** [comment]
@kentcdodds Would you mind cutting a new release with this? I know this has caused a couple issues with the prettier-atom package since prettier-atom is at 0.22.0 and this was previously at 0.19.0. I'll do my best to keep prettier-eslint up to date for you 🤞

**Comment by kentcdodds** [comment]
So `prettier-atom` is no longer in sync with `prettier`.

Also, this has already been released! [AUTOMATICALLY](https://egghead.io/lessons/javascript-how-to-write-a-javascript-library-automating-releases-with-semantic-release?course=how-to-write-an-open-source-javascript-library) ✨ ❤️ 

Thanks so much! I should probably get @jlongster to enable Greenkeeper integration in the prettier org so I can just use that again :)

**Comment by mgmcdermott** [comment]
It's not just that prettier-atom is out of sync with prettier, it's that prettier-atom uses this package if the eslint integration option is checked. Here's an example (and partly how I ended up contributing here): https://github.com/prettier/prettier/issues/925

**Comment by kentcdodds** [comment]
Ah, thanks for the context. I now understand what you meant when you referenced the version numbers. @jlongster, if we could enable the Greenkeeper integration on the prettier org, then I could enable it on this repo to make sure we stay up to date. Thanks again!

**Comment by mgmcdermott** [comment]
Also, it looks like none of my commits were relevant so no release was done 😢 
https://travis-ci.org/prettier/prettier-eslint#L295

**Comment by kentcdodds** [comment]
Ah, yes, I should have labeled it as fix.

I'm on my way out. I'll release when I'm back later today.

**Comment by kentcdodds** [comment]
Alrighty, it should be released by now. Check this out: https://github.com/prettier/prettier-eslint/blob/master/other/manual-release.md

😏

**Pull request merged**
